version: "3.8"

x-common-service: &common-service
  build:
    context: .
    dockerfile: dockerfiles/Dockerfile
  volumes:
    - ./src:/app/src
    - ./data:/app/data
    - ./models:/app/models
  working_dir: /app
  restart: "no"

services:
  import_raw_data:
    <<: *common-service
    command: ["python", "src/data/import_raw_data.py"]
    healthcheck:
      test: ["CMD", "sh", "-c", "test -f /app/data/raw/tags.csv"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  build_features:
    <<: *common-service
    command: ["python", "src/data/build_features.py"]
    depends_on:
      import_raw_data:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "sh", "-c", "test -f /app/data/processed/movie_matrix.csv"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  train:
    <<: *common-service
    command: ["python", "src/models/train.py"]
    depends_on:
       build_features:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "sh", "-c", "test -f /app/models/model.pkl"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  predict:
    <<: *common-service
    command: ["python", "src/models/predict.py"]

  evaluate:
    <<: *common-service
    command: ["python", "src/models/evaluate.py"]
    volumes:
      - ./metrics:/app/metrics

  api:
    <<: *common-service
    ports:
      - "8000:8000"
    command: ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: "no"
