version: "3.8"

x-common-service: &common-service
  build:
    context: .
    dockerfile: dockerfiles/Dockerfile
  volumes:
    - ./src:/app/src
    - ./data:/app/data
    - ./models:/app/models
  working_dir: /app
  restart: "no"

services:
  import_raw_data:
    <<: *common-service
    command: ["python", "src/data/import_raw_data.py"]

  build-features:
    <<: *common-service
    command: ["python", "src/data/build_features.py"]

  train:
    <<: *common-service
    command: ["python", "src/models/train.py"]

  predict:
    <<: *common-service
    command: ["python", "src/models/predict.py"]

  evaluate:
    <<: *common-service
    command: ["python", "src/models/evaluate.py"]
    volumes:
      - ./metrics:/app/metrics

  api:
    <<: *common-service
    ports:
      - "8000:8000"
    command: ["uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
    restart: "no"
