version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: src/api/Dockerfile 
    ports:
      - "8000:8000"
  data-service:
    build:
      context: .
      dockerfile: src/data/Dockerfile
  build-features:
    build:
      context: .
      dockerfile: src/data/Dockerfile
  train:
    build:
      context: . 
      dockerfile: src/models/train/Dockerfile 
  predict:
    build:
      context: .
      dockerfile: src/models/predict/Dockerfile  
  evaluate:
    build:
      context: .
      dockerfile: src/models/evaluate/Dockerfile
