version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: src/api/Dockerfile
    ports:
      - "8000:8000"
  data-service:
    build:
      context: .
      dockerfile: src/data/Dockerfile
    environment:
      - DAGSHUB_REPO=${DAGSHUB_REPO}
      - DAGSHUB_TOKEN=${DAGSHUB_TOKEN}
  build-features:
    build:
      context: .
      dockerfile: src/features/Dockerfile
  train:
    build:
      context: . 
      dockerfile: src/models/train/Dockerfile 
  predict:
    build:
      context: .
      dockerfile: src/models/predict/Dockerfile  
  evaluate:
    build:
      context: .
      dockerfile: src/models/evaluate/Dockerfile
