# Utiliser une image officielle Python comme base
FROM python:3.10-slim

# Définir le répertoire de travail à l'intérieur du conteneur
WORKDIR /app

# Installer les dépendances
COPY ./src/models /app
COPY ./data /app/data
COPY ./models /app/models
COPY ./requirements/models.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Commande par défaut 
CMD ["python", "train.py"]