# Dockerfile pour le service d'évaluation
FROM python:3.10-slim

# Définir l'UID et le GID en dur
ENV UID=1000
ENV GID=1000

# Créer un groupe et un utilisateur avec les UID/GID spécifiés
RUN groupadd -g $GID appgroup && \
    useradd -m -u $UID -g appgroup appuser

# Passer à cet utilisateur non root

USER appuser
# Définir le répertoire de travail
WORKDIR /app

# Installer les dépendances
COPY ./src/data /app
COPY ./requirements/data.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Commande par défaut 
CMD ["python", "import_raw_data.py"]