# Dockerfile pour le service d'évaluation
FROM python:3.10-slim

# Définir le répertoire de travail
WORKDIR /app

# Installer les dépendances
COPY ./src/data /app
COPY ./requirements/data.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# Commande par défaut 
CMD ["python", "import_raw_data.py"]