# Utiliser une image officielle Python comme base
FROM python:3.10-slim

# Définir le répertoire de travail à l'intérieur du conteneur
WORKDIR /app

COPY ./requirements/requirements.txt /app/requirements.txt

# Installer les dépendances
RUN apt-get update && apt-get install -y git
RUN pip install --no-cache-dir -r /app/requirements.txt

CMD ["python", "main.py"]