name: Check Permissions Before and After Each Step

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

env: # Declare global environment variables
  AIRFLOW_UID: 50000
  DOCKER_GROUP_GID: "" # Placeholder; will be updated dynamically

jobs:
  run-airflow:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install Python and Airflow
      - name: Install Python and Airflow
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install -r requirements.txt
          pip3 install apache-airflow

      # Step 3: Detect Docker Group ID (GID)
      - name: Detect Docker Group ID
        id: detect-docker-gid
        run: |
          DOCKER_GROUP_GID=$(getent group docker | cut -d: -f3)
          echo "Docker Group GID: $DOCKER_GROUP_GID"
          echo "DOCKER_GROUP_GID=$DOCKER_GROUP_GID" >> $GITHUB_ENV

      # Step 4: Create Airflow User with Correct GID
      - name: Create Airflow User with Docker Permissions
        run: |
          sudo groupadd -g $DOCKER_GROUP_GID docker || echo "Docker group already exists"
          sudo useradd -m -u $AIRFLOW_UID -g $DOCKER_GROUP_GID airflow || echo "Airflow user already exists"
          sudo usermod -aG docker airflow
          id airflow

      # Step 5: Adjust Docker Socket Permissions
      - name: Fix Docker Socket Permissions
        run: |
          sudo chmod 666 /var/run/docker.sock

      # Step 6: Setup Airflow Logs Directory
      - name: Setup Airflow Logs Directory
        run: |
          sudo mkdir -p airflow/logs
          sudo chown airflow:docker airflow/logs
          sudo chmod -R 755 airflow/logs