name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build, Test, and Push Services
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker images for all services
      - name: Build service images
        run: |
          docker-compose build

      # Run and validate import_raw_data service
      - name: Validate import_raw_data service
        run: |
          docker-compose up -d import_raw_data
          echo "Waiting for import_raw_data to complete..."
          docker wait import_raw_data
          docker logs import_raw_data

      # Run and validate build_features service
      - name: Validate build_features service
        run: |
          docker-compose up -d build_features
          echo "Waiting for build_features to complete..."
          docker wait build_features
          docker logs build_features

      # Run and validate train service
      - name: Validate train service
        run: |
          docker-compose up -d train
          echo "Waiting for train to complete..."
          docker wait train
          docker logs train

      # Run and validate predict service
      - name: Validate predict service
        run: |
          docker-compose up -d predict
          echo "Waiting for predict to complete..."
          docker wait predict
          docker logs predict

      # Run and validate evaluate service
      - name: Validate evaluate service
        run: |
          docker-compose up -d evaluate
          echo "Waiting for evaluate to complete..."
          docker wait evaluate
          docker logs evaluate

      # Run and validate API service
      - name: Validate API service
        run: |
          docker-compose up -d api
          echo "Waiting for API to start..."
          sleep 10  # Give API some time to start
          docker logs api

      # Push Docker images to the registry
      - name: Push service images
        run: |
          docker-compose push